### ISSUE TITLE
yarn 添加 @nuxtjs/eslint-config-typescript 报错。pnpm 正常

### ISSUE THREAD

**Issue by xuxchao** [nuxt/eslint-config#270] opened 2023-03-01 06:12 UTC
1. 通过 pnpm dlx nuxi init <project-name> 创建一个新项目。
2. 添加 @nuxtjs/eslint-config-typescript 包
3. pnpm install
4. package.json 添加 "lint": "eslint --ext .ts,.js,.cjs,.vue .",
5. 执行 pnpm lint 正常。

3,5 的命令换成 yarn。会报错
![image](https://user-images.githubusercontent.com/28293069/222059433-03087ec8-eb1d-43b4-bec0-c0c24928b355.png)

**Comment by toto6038** [comment] 2023-11-17 10:11
English please

**Comment by antfu** [comment] 2024-03-18 17:15
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-03-18 17:15 UTC
