### ISSUE TITLE
Whitelisting auto-imported function

### ISSUE THREAD

**Issue by OysterD3** [nuxt/eslint-config#304] opened 2023-08-26 21:07 UTC
Currently, it doesn't have any whitelisted function for eslint.
It will be caused eslint to give `no-undef` error warning when we are using `eslint:recommended`

We can just follow the way that https://github.com/antfu/unplugin-auto-import did

**Comment by ColtHands** [comment] 2023-09-10 18:27
+ to this

**Comment by Revadike** [comment] 2023-12-19 17:15
Dupe of https://github.com/nuxt/eslint-config/issues/309

**Closed** 2023-12-19 17:22 UTC
