### ISSUE TITLE
Failed to load plugin 'unicorn'

### ISSUE THREAD

**Issue by daltonrooney** [nuxt/eslint-config#81] opened 2020-02-12 17:23 UTC
I'm getting the following warning on a new Nuxt installation (using npx create-nuxt-app)

```
WARN Compiled with 1 warnings
Module Warning (from ./node_modules/eslint-loader/dist/cjs.js):
Failed to load plugin 'unicorn' declared in '.eslintrc.js » @nuxtjs/eslint-config': Invalid regular expression: /(?<before>(?:^|[^\\])(?:\\\\)*)\\(?<data>x[\da-f]
{2}|u[\da-f]{4}|u{[\da-f]+})/: Invalid group
```

Any thoughts on troubleshooting?

**Comment by manniL** [comment] 2020-02-16 22:32
Duplicate of https://github.com/nuxt/nuxt.js/issues/6963

**Closed by manniL** 2020-02-16 22:32 UTC
