### ISSUE TITLE
please support airbnb!!! :( 

### ISSUE THREAD

**Issue by ahsandev2019** [nuxt/eslint-config#105] opened 2020-07-08 07:51 UTC
im using airbnb for the past year and i found it "more beautifull" than other 
and for trends its far better 
https://www.npmtrends.com/eslint-config-airbnb-vs-eslint-config-google-vs-standard

**Comment by manniL** [comment] 2020-07-08 12:09
Duplicate of #41

**Closed by manniL** 2020-07-08 12:09 UTC
